name: ci-main

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Maven Build
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: Build and Deploy Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t drive-and-deliver-app .
